# Chapter 6 - Other Popular Machine Learning Methods
## Segment 2 - A neural network with a Perceptron

In [1]:
import numpy as np
import pandas as pd
import sklearn

from pandas import Series, DataFrame
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
from sklearn.linear_model import Perceptron

In [3]:
iris = datasets.load_iris()

X = iris.data
y = iris.target

X[0:10,]

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1]])

In [4]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [5]:
standardize = StandardScaler()

standardized_X_test = standardize.fit_transform(X_test)

standardized_X_train = standardize.fit_transform(X_train)

In [6]:
standardized_X_test[0:10,]

array([[ 0.3940552 ,  0.64052686,  0.9576819 ,  1.46587296],
       [-1.37919321, -0.18595941, -1.47024404, -1.58067024],
       [-0.1970276 , -1.01244568,  0.03275773, -0.12362784],
       [ 0.3940552 , -0.80582411,  0.55302758,  0.67112256],
       [ 0.15762208, -0.59920254,  0.03275773,  0.00883056],
       [ 0.86692145,  0.02066216,  0.43741206,  0.27374736],
       [-0.90632697,  0.84714842, -1.41243628, -1.44821184],
       [-1.02454353,  0.43390529, -1.29682076, -1.05083664],
       [ 1.69443737, -0.59920254,  1.2467207 ,  0.80358096],
       [-0.66989385, -0.18595941,  0.32179653,  0.27374736]])

In [7]:
perceptron = Perceptron(max_iter=50, eta0=0.15, tol=1e-3, random_state=15)

perceptron.fit(standardized_X_train, y_train.ravel())

Perceptron(eta0=0.15, max_iter=50, random_state=15)

In [8]:
y_pred = perceptron.predict(standardized_X_test)

In [9]:
print(y_test)

[2 0 1 2 1 1 0 0 2 1 1 0 1 2 2 1 0 1 2 2 2 0 1 1 2 2 0 2 0 0]


In [10]:
print(y_pred)

[2 0 1 2 1 1 0 0 2 2 1 0 0 2 2 1 0 2 2 2 2 0 1 1 2 2 0 2 0 0]


In [11]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.90      1.00      0.95         9
           1       1.00      0.70      0.82        10
           2       0.85      1.00      0.92        11

    accuracy                           0.90        30
   macro avg       0.92      0.90      0.90        30
weighted avg       0.91      0.90      0.89        30

